# Generated by Django 4.2.3 on 2023-07-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_home_inicio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nosotros',
            new_name='Suscripcion',
        ),
        migrations.DeleteModel(
            name='Inicio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='email',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
