# Generated by Django 4.2.3 on 2023-07-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_nosotros_suscripcion_delete_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='apellido',
            new_name='encargado',
        ),
    ]
